### ISSUE TITLE
Can we support versioning for each blob

### ISSUE THREAD

**Issue by lylex** [nanopack/hoarder#21]
Hi,

I find this project is what I need. But only one little defect, which is version is not supported for the blob. So do we have the plan to have this feature?

Thanks in advance.

**Comment by danhunsaker** [comment]
Versioning isn't supported because the intended use case for Hoarder is storing blobs that are already snapshots themselves. Deployable codebases, data backups, and similar. Versioning these wouldn't make much sense - if you have more than one version of a snapshot, it isn't really a snapshot anymore.

That isn't to say versioning couldn't be added, just that it falls outside the intended usage.

**Comment by lylex** [comment]
OK, that makes sense to me. Thanks.
